### PR TITLE
[Fix]：add initial_sentences param and fix custom tokenizer does not work

### PR DESCRIPTION
**Pull request by ljhssga**
Feature Enhancement and Bug Fixes for Semantic Chunking
1. SemanticChunker: Added initial_sentence Parameter

Introduced a new initial_sentence parameter to the SemanticChunker class
Allows users to specify the number of sentences used as initial context when starting a new chunk in accumulation mode
Default value set to 1
Provides increased flexibility in controlling semantic-based sentence grouping

2. Improved Tokenizer Validation in BaseChunker

Enhanced input validation for the tokenizer_or_token_counter parameter
Added support for methods using inspect.ismethod() check
Increases robustness of tokenizer input processing
Enables more versatile tokenization strategies

Fixes for Current Version (v0.2.2)

Resolves TypeError when setting initial_sentences
Addresses ValueError related to custom tokenizer usage
Supports broader range of tokenization approaches

### CODE REVIEW

**Comment by ljhssga** [comment]
Fixes https://github.com/chonkie-ai/chonkie/issues/64

**Comment by bhavnicksm** [comment]
Hey @ljhssga!

Thanks for opening a PR! 😊

Actually quite valid that the argument `initial_sentences` doesn't work, it's because it was removed in version `v0.2.2`, and the documentation needs to be update. Sorry for the confusion 🥹

We are using the argument `similarity_window` and `min_sentences` to control the behaviour of `initial_sentences`, wherein the `min_sentences` is the sentences it would start with in the `mode="cumulative"` which we were using by default earlier. 

Currently, `mode="window"` is set to default and hence uses the `similarity_window` and `min_sentences` together to get the final result. 

Would try to update the documentation ASAP, but I am pretty swamped with some features at the moment 🥲

Thank you for the patience 🙏

**Comment by ljhssga** [comment]
> Hey @ljhssga!
> 
> Thanks for opening a PR! 😊
> 
> Actually quite valid that the argument `initial_sentences` doesn't work, it's because it was removed in version `v0.2.2`, and the documentation needs to be update. Sorry for the confusion 🥹
> 
> We are using the argument `similarity_window` and `min_sentences` to control the behaviour of `initial_sentences`, wherein the `min_sentences` is the sentences it would start with in the `mode="cumulative"` which we were using by default earlier.
> 
> Currently, `mode="window"` is set to default and hence uses the `similarity_window` and `min_sentences` together to get the final result.
> 
> Would try to update the documentation ASAP, but I am pretty swamped with some features at the moment 🥲
> 
> Thank you for the patience 🙏

I see.And what about https://github.com/chonkie-ai/chonkie/issues/64

**Comment by bhavnicksm** [comment]
Closing this PR since the docs have been updated~

Thanks! 😊

**Pull request closed without merging**
